/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.DepartamentoDAO;
import modelo.DepartamentoVO;
import modelo.ProvinciaDAO;
import modelo.ProvinciaVO;
import modelo.clienteDAO;
import modelo.clienteVO;
import modelo.validaciones;
import modelo.zonaDAO;

/**
 *
 * @author nycha
 */
public class modificarC extends javax.swing.JFrame {
 DepartamentoDAO de = new DepartamentoDAO();
    ProvinciaDAO pr = new ProvinciaDAO();

    /**
     * Creates new form eliminarC
     */
    public modificarC() {
        initComponents();
        this.setLocationRelativeTo(null);
        bloquear();
        leer();
        jButton3.setEnabled(false);
                    de.listar_departamento(ciudad);

    }

    private void leer(){
        clienteVO clienteVO=new clienteVO();
        clienteDAO clienteDAO=new clienteDAO();
        ArrayList <clienteVO> lista = new ArrayList <clienteVO>();
           lista=clienteDAO.mostrarCliente();
           DefaultTableModel modeloT = new DefaultTableModel();
           jTableMod.setModel(modeloT);
           modeloT.addColumn("Cedula");
           modeloT.addColumn("Nombre");
           modeloT.addColumn("Celular");
           modeloT.addColumn("Correo");
           modeloT.addColumn("Ciudad");
           modeloT.addColumn("Zona");
           modeloT.addColumn("Calle principal");
           modeloT.addColumn("Calle secundaria");
           modeloT.addColumn("Lote");
           Object[] columna = new Object[9];
           for (int i=0;i<lista.size();i++){
               columna[0]=lista.get(i).getIdentificacion();
               columna[1]=lista.get(i).getNombre();
               columna[2]=lista.get(i).getTelefono();
               columna[3]=lista.get(i).getCorreo();
               columna[4]=lista.get(i).getCiudad();
               columna[5]=lista.get(i).getZona();
               columna[6]=lista.get(i).getCalleP();
               columna[7]=lista.get(i).getCalleS();
               columna[8]=lista.get(i).getLote();
               modeloT.addRow(columna);
           }
    
    }
    public void bloquear(){
         cedula.setEditable(false);
         cedula.setEnabled(true);
         nombre.setEditable(false);
         nombre.setEnabled(true);
         celular.setEditable(false);
         celular.setEnabled(true);
         correo.setEditable(false);
         correo.setEnabled(true);
         ciudad.setEditable(false);
         ciudad.setEnabled(true);
         zona1.setEditable(false);
         zona1.setEnabled(true);
         calleP.setEditable(false);
         calleP.setEnabled(true);
         calleS.setEditable(false);
         calleS.setEnabled(true);
         lote.setEditable(false);
         lote.setEnabled(true);


    }
    public void desbloquear(){
         cedula.setEditable(false);
         cedula.setEnabled(true);
         nombre.setEditable(true);
         nombre.setEnabled(true);
         celular.setEditable(true);
         celular.setEnabled(true);
         correo.setEditable(true);
         correo.setEnabled(true);
         ciudad.setEditable(false);
         ciudad.setEnabled(true);
         zona1.setEditable(false);
         zona1.setEnabled(true);
         calleP.setEditable(true);
         calleP.setEnabled(true);
         calleS.setEditable(true);
         calleS.setEnabled(true);
         lote.setEditable(true);
         lote.setEnabled(true);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMod = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        calleS = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lote = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        celular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        calleP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        ciudad = new javax.swing.JComboBox<>();
        zona1 = new javax.swing.JComboBox<>();

        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificarcliente.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableMod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableModMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableModMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMod);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("DATOS DEL CLIENTE A MODIFICAR");

        jButton3.setBackground(new java.awt.Color(153, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cedula");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Ciudad");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Calle S");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Zona");

        cedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedulaKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Celular");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Correo");

        nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Lote/numCasa");

        celular.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        celular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celularActionPerformed(evt);
            }
        });
        celular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                celularKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Calle P");

        correo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoActionPerformed(evt);
            }
        });
        correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                correoKeyTyped(evt);
            }
        });

        ciudad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ciudad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ciudadItemStateChanged(evt);
            }
        });

        zona1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zona1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                zona1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombre)
                                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(calleP)
                                    .addComponent(calleS, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lote, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ciudad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(zona1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)))
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton3))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(celular, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ciudad)
                                .addGap(71, 71, 71))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(zona1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calleP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(calleS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lote, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(53, 53, 53))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cliente cliente=new cliente();
        cliente.setVisible(true);

        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int fila=jTableMod.getSelectedRow();
        if(fila>=0){
        cedula.setText(jTableMod.getValueAt(jTableMod.getSelectedRow(),0).toString());
        nombre.setText(jTableMod.getValueAt(jTableMod.getSelectedRow(),1).toString());
        celular.setText(jTableMod.getValueAt(jTableMod.getSelectedRow(),2).toString());
        correo.setText(jTableMod.getValueAt(jTableMod.getSelectedRow(),3).toString());
        calleP.setText(jTableMod.getValueAt(jTableMod.getSelectedRow(),6).toString());
        calleS.setText(jTableMod.getValueAt(jTableMod.getSelectedRow(),7).toString());
        lote.setText(jTableMod.getValueAt(jTableMod.getSelectedRow(),8).toString());
        }else{
            JOptionPane.showMessageDialog(null,"No ha seleccionado ningun campo");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTableModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableModMouseClicked
        int fila = this.jTableMod.getSelectedRow();
            this.cedula.setText(jTableMod.getValueAt(fila,0).toString());
            this.nombre.setText(jTableMod.getValueAt(fila,1).toString());
            this.celular.setText(jTableMod.getValueAt(fila,2).toString());
            this.correo.setText(jTableMod.getValueAt(fila,3).toString());
            this.calleP.setText(jTableMod.getValueAt(fila,6).toString());
            this.calleS.setText(jTableMod.getValueAt(fila,7).toString());
            this.lote.setText(jTableMod.getValueAt(fila,8).toString());
        desbloquear();
        jButton3.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableModMouseClicked

    private void jTableModMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableModMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableModMouseEntered

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clienteDAO clienteDAO=new clienteDAO();
        clienteVO clienteVO=new clienteVO();
        validaciones val=new validaciones();
                if(nombre.getText().isEmpty()||calleP.getText().isEmpty()||calleS.getText().isEmpty()||lote.getText().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Faltan campos de llenar");

        }else{

        if(val.verificarEmail(correo.getText())==true){
            Pattern pat1 = Pattern.compile("^[0]{1}[9]{1}[0-9]{8}$");
            Matcher mat1 = pat1.matcher(celular.getText());

            if(mat1.matches()){
                clienteVO.setIdentificacion(cedula.getText());
                clienteVO.setNombre(nombre.getText());
                clienteVO.setTelefono(celular.getText());
                clienteVO.setCorreo(correo.getText());
                clienteVO.setCiudad(ciudad.getSelectedItem().toString());
                clienteVO.setZona(zona1.getSelectedItem().toString());
                clienteVO.setCalleP(calleP.getText());
                clienteVO.setCalleS(calleS.getText());
                clienteVO.setLote(lote.getText());
                clienteDAO.modificarClienteIdentificacion(clienteVO);
         cedula.setEditable(false);
         cedula.setEnabled(true);
         nombre.setEditable(false);
         nombre.setEnabled(true);
         celular.setEditable(false);
         celular.setEnabled(true);
         correo.setEditable(false);
         correo.setEnabled(true);
         ciudad.setEditable(false);
         ciudad.setEnabled(true);
         zona1.setEditable(false);
         zona1.setEnabled(true);
         calleP.setEditable(false);
         calleP.setEnabled(true);
         calleS.setEditable(false);
         calleS.setEnabled(true);
         lote.setEditable(false);
         lote.setEnabled(true);


                cedula.setText("");
                nombre.setText("");
                celular.setText("");
                correo.setText("");
                calleP.setText("");
                calleS.setText("");
                lote.setText("");
                leer();
            }else{
                JOptionPane.showMessageDialog(null, "Celular incorrecto");

            }

        }else{
            JOptionPane.showMessageDialog(null, "Correo incorrecto");

        }
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaKeyTyped
        char a =evt.getKeyChar();
        if (!((int)a>=48 && (int)a<=57)){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaKeyTyped

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        char a =evt.getKeyChar();
        if (( ((int)a>=33 && (int)a<=64))||((int)a>=91 && (int)a<=96)|| ((int)a>=123 && (int)a<=223)){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreKeyTyped

    private void celularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celularActionPerformed

    private void celularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_celularKeyTyped
        char a =evt.getKeyChar();
        if (!((int)a>=48 && (int)a<=57)){
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_celularKeyTyped

    private void correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoActionPerformed

    private void correoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_correoKeyTyped
        char a =evt.getKeyChar();

        if ( ( ((int)a>=32 && (int)a<=45)) || ( ((int)a>=58 && (int)a<=63))||((int)a>=91 && (int)a<=94)|| ((int)a>=123 && (int)a<=255)|| ( ((int)a>=47 && (int)a<=47))){
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_correoKeyTyped

    private void ciudadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ciudadItemStateChanged

        DepartamentoVO d_vo = (DepartamentoVO)this.ciudad.getSelectedItem();
        int id_de = d_vo.getIdDepartamento();
        String n = d_vo.getDepartamento();

        pr.listar_provincia(zona1, id_de);
    }//GEN-LAST:event_ciudadItemStateChanged

    private void zona1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_zona1ItemStateChanged
       ProvinciaVO p_vo = (ProvinciaVO)this.zona1.getSelectedItem();
        int id_di = p_vo.getIdProvincia();
        String n = p_vo.getProvincia();
    }//GEN-LAST:event_zona1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificarC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField calleP;
    private javax.swing.JTextField calleS;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField celular;
    private javax.swing.JComboBox<String> ciudad;
    private javax.swing.JTextField correo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableMod;
    private javax.swing.JTextField lote;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> zona1;
    // End of variables declaration//GEN-END:variables
}
